### ISSUE TITLE
Consider a more ad-hoc way for the FINOS community to socialise 

### ISSUE THREAD

**Issue by adds68** [finos/community#100]
# FINOS Community Socialisation
It would be nice to have a more ad-hoc way for members of the FinOS community to communicate/collaborate together.

# Proposed Solution
A solution to this would be some form of real time communication platform, or a moderated Forum.

# Current State
The current state is communications are done via Github projects and bi-weekly video calls.

# Existing Solutions

## IRC
https://freenode.net/

## Slack
https://slack.com/intl/en-gb/

## Rocket.chat
https://rocket.chat/

## Discourse
https://www.discourse.org/

**Comment by mvanbuskirk** [comment]
+1 to this. I would vote for Slack.

**Comment by daniela-g-zheleva-db** [comment]
+1 Symphony could be another option.

**Comment by jjardon** [comment]
+1 to this

I'd vote for matrix: https://matrix.org/
- e2e encrytion
- federated
- FOSS
- Used in large scale organizations (governments)

**Comment by mcleo-d** [comment]
Hi @adds68,

Thank you for contributing this issue and great question. It's great to also see everyone contributing to potential solutions.

I have now taken the issue forward inside FINOS to investigate and report back to the FINOS team. I thought you'd like to know about a similar issue that @ashukla13, @awallgren and the DevOps Mutualization SIG raised to investigate ... 

- https://github.com/finos/devops-mutualization/issues/1

By linking the resolution of this issue to the DevOps Mutualization SIG, we could potentially feed ideas and proposed solutions into the FINOS community and wider FINOS initiatives.

Thanks once again and speak soon.

James.

**Comment by mcleo-d** [comment]
Hi everyone 👋 

Following #100 raised by @adds68, FINOS is proud to announce a dedicated [FINOS Slack](https://finos-lf.slack.com/) and access to [GitHub Team Discussions](https://help.github.com/en/articles/about-team-discussions) for FINOS Projects, SIGs and the wider FINOS Community.

As documented in pull request https://github.com/finos/open-developer-platform/pull/206 that updates the [FINOS ODP Microsite](https://odp.finos.org/), the following extract highlights the available options and how to gain access through the FINOS team.

## FINOS Communication Platform Options
In order to track threaded conversations - among FINOS Project / SIG team members, external collaborators and consumers - it is possible to use [GitHub Issues](https://help.github.com/en/github/managing-your-work-on-github/about-issues), with the following limitations:

1. The scope of the conversations is always public, whereas there may be sensitive conversations across project leaders that may require to be confidential
2. Issue comments are flat, although mentions and quoting can be used to follow multiple conversation threads.

### GitHub Team Discussions

A more advanced way is to use [GitHub Team Discussions](https://help.github.com/en/articles/about-team-discussions):

1. Can be created as private, which are accessible only by team members
2. Can be created as public to all GitHub FINOS org members
3. Cannot be created at public to non FINOS member or unauthenticated visitors, so GitHub Issues is the only option for that.

Both features **support email notifications** and the ability to post a comment by answering to it. Simply raise a [FINOS Slack Channel / GitHub Team Discussions Request](https://github.com/finos/open-developer-platform/issues/new?assignees=mcleo-d&labels=comms-channel-request&template=Communication_channel_request.md&title=) to enable GitHub Team Discussions for FINOS Project and SIG teams. 

### FINOS Slack

The [FINOS Slack](https://finos-lf.slack.com/) brings the FINOS Community together in a Slack Workspace dedicated to **_"public"_** conversations and made available to all FINOS Projects and Special Interest Groups. 

The FINOS Community can access the FINOS Slack by visiting https://finos-lf.slack.com/ and requesting access to join.

FINOS Project and SIG Leads, simply raise a [FINOS Slack Channel / GitHub Team Discussions Request](https://github.com/finos/open-developer-platform/issues/new?assignees=mcleo-d&labels=comms-channel-request&template=Communication_channel_request.md&title=) to create a Slack Channel for your FINOS Project or Special Interest Group.

All participants in the FINOS Slack are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

It's extremely important that all participants in the FINOS Slack do not participate in any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

**Comment by RichardWagener365** [comment]
This is great news - Well done

**Comment by mcleo-d** [comment]
Thanks @RichardWagener365

Feel free to email help@finos.org to request an invitation to join the FINOS Slack 👍 

James.
