### ISSUE TITLE
Project Archiving at the TSC

### ISSUE THREAD

**Issue by robmoffat** [finos/community#203]
HI,

I would like us to discuss the topic of FINOS project off boarding (or archiving) at the TSC.   I would like the TSC to discuss and decide on what criteria should make a project a candidate for off-boarding.  

Having done that, FINOS can build a report like this one:  https://github.com/robmoffat/landscape-scanning/blob/main/scan.csv

Which will contain the list of projects that we might want to archive.  This will then be up to the TSC to make a decision on, per-project.

**Comment by martin-traverse** [comment]
Hi, I had a look at this report, are you suggesting we score projects based on compliance criteria and recommend projects for archiving at a certain threshold? It's a punchy way to encourage compliance! I'd think we need some sort of warning process to give projects time to remediate

We'd need some documentation on how these violations are detected I think. For example, my own project definitely has CVE scanning across multiple languages, but is this was not detected by the tool and reported as a violation. Perhaps there is some standard layout of project build files that is being used for detection? We'd need to make these kind of details know, so project owns can follow the reuqired patterns to make sure everything is picked up correctly.

As well as compliance, should we look at activity? Certianly for software projects this could be a key metric. Time since last commit is perhaps the most basic. We could get more detailed on issues, issue resolution etc., maybe that's a second stage.

**Comment by jonfreedman** [comment]
Example archived project: https://github.com/symphonyoss/hubot-symphony

Note that some standard metrics will be confusing - we had that setup with Dependabot so there were frequent PRs and I merged all the ones that didn't break tests, but that wasn't "real" activity.

**Comment by maoo** [comment]
@rikoe - raised PR on https://github.com/finos/community/pull/290 . Could you please review and suggest edits? Thanks!

**Comment by maoo** [comment]
PR merged, thanks @rikoe ! I'm closing this issue, please reopen if you think there are some other pending tasks. Thanks!
