### ISSUE TITLE
Software Project Contribution and Onboarding - Regular Table

### ISSUE THREAD

**Issue by neilslinger** [finos/community#218]
Please note that only FINOS members can propose new projects. If you're interested in membership, see https://www.finos.org/membership-benefits#become-a-member.

# Onboarding Process

Completing an onboarding of a project into FINOS requires following these 5 main steps:  

1.  **Describing the Contribution** _led by contributor_
2.  **FINOS Approval** _led by FINOS Point of Contact (POC)_
3.  **Preparing for Onboarding** _led by contributor_
4.  **Onboarding** _completed by FINOS Infra_
5.  **Announcement** _led by FINOS Point of Contact (POC)_

# 1. Describing The Contribution

This is a list of questions that need to be answered by the contributor in order to allow a new project to pass to the approval stage of onboarding.

## Business Problem
Provide a high-performance and easy-to-integrate table component.
 
## Proposed Solution
A Javascript library for the browser, regular-table exports a [custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) named <regular-table>, which renders a regular HTML ```<table>``` to a sticky position within a scollable viewport. Only visible cells are rendered and queried from a natively async virtual data model, making regular-table ideal for enormous or remote data sets. Use it to build Data Grids, Spreadsheets, Pivot Tables, File Trees, or anytime you need:

Just a regular ```<table>```.
* Virtually rendered for high-performance.
* async data model handles slow, remote, enormous, and/or distributed backends.
* Easy to style, works with any regular CSS for ```<table>```.
* Small bundle size, no dependencies.

## Tentative Roadmap
This library is already used by the [Perspective](https://github.com/finos/perspective) project and features are added as required.
 
## Current State
Has been released and in-use for over two years.
 
## Existing Materials
*If materials already exist, provide a link to them that Foundation staff can access - if it's in a private GitHub.com repositories, you should invite the finos-admin user with R/O permissions to those repositories*

 - [x] GitHub
   - [x] URL for the repository: https://github.com/jpmorganchase/regular-table
   - [x] Project Name: regular-table
   - [x] @finos-admin has been given read-only permissions if private
 - [x] Is Continuous Integration used?
 - [x] Was the project ever released? _(yes)_ 
   - [x] If so, are releases public? _(yes)_ 
   - [x] And what's the latest released version? v0.5.6
 - [x] Existing Project Documentation: https://github.com/jpmorganchase/regular-table/blob/master/api.md
 - [x] Does the name have a registered trademark? _(no)_
 - [x] Is there a logo? _(yes)_

### Maintainers
*Who will be the [project maintainer(s)](https://odp.finos.org/docs/finos-maintainers-cheatsheet/#maintainer-responsibilities-and-available-resources)? Provide full name, affiliation, work email address, and GitHub / GitLab username.*

|Name                        |Affiliation              |Work Email Address             |Github / GitLab username              |
|----------------------------|-------------------------|-------------------------------|--------------------------------------|
|Andrew Stein                |Prospective              |steinlink@gmail.com               |@texodus                       |

### Confirmed contributors
*If applicable, list all of the individuals that have expressed interest in and/or are committed to contributing to this project, including full name, affiliation, work email address, and GitHub.com username*

|Name                        |Affiliation              |Work Email Address             |Github / GitLab username              |
|----------------------------|-------------------------|-------------------------------|--------------------------------------|
|Andrew Stein                |Prospective              |steinlink@gmail.com               |@texodus                       |
|Josh Hawkins                |JP Morgan              |josh.r.hawk@gmail.com               |@JHawk                       |

### Target Contributors
*Describe the contributor profile (background, position, organization) you would like to get contributions from.*

## Project Communication Channel(s)

- GitHub Issues

## Understanding FINOS Onboarding Requirements

As a project onboarding into FINOS, you will need to familiarize yourself and your contributor team with the following materials:

 - [x] [FINOS overview](https://www.finos.org/hubfs/An%20Introduction%20to%20FINOS.pdf) (if necessary)
 - [x] [FINOS Maintainers cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet/)
 - [x] [FINOS Project/Standards Governance](https://community.finos.org/docs/governance)
 - [x] [FINOS Project Lifecycle](https://community.finos.org/docs/governance/Software-Projects/project-lifecycle)
 - [x] Notify help@finos.org that you have completed the _describing the contribution_ section. 

# 2. FINOS Approval

Below is the list of tasks that the **FINOS Team** go through in order to complete the FINOS approval process.  At this point, a FINOS Point-of-Contact (POC) should be assigned to this GitHub issue.

**Please do not edit these contents when completing part 1, "describing the contribution" above.**

## Record The Contribution
- [x] Submit contribution to LF by opening a ticket via https://jira.linuxfoundation.org/browse/SS and marking contribution as "Exploratory"; attach a summary of the **Business Problem** and **Proposed Solution** (above) of the project. - https://jira.linuxfoundation.org/browse/SS-995

## Kick-off meeting
- [x] Set up kick-off meeting with project leads
- [x] Run kick-off meeting
  - [x] Walk through the checklist in part 1, ensure all the questions are answered and remove items that don't apply

## FINOS Contrib POC
- [x] Identify and Assign FINOS Project Coordinator - @maoo
- [x] Identify and Assign FINOS Strategic Advisor - @jgavronsky 

## Technical Steering Committee Approval

- [x] Prioritise this issue on the [TSC Backlog](https://github.com/orgs/finos/projects/39)
- [x] Assign this issue to @colineberhardt
- [x] Add the `ready-for-tsc` label
- [x] FINOS TSC approves/rejects the contribution
- [x] Ask @jgavronsky to mark contribution as "Engaged" within LF systems

## TSC Findings / Report
*TSC to enter findings summary here.*

# 3. Preparing For Onboarding

Before the FINOS team can onboard your project, there are a few housekeeping that need to be taken care of.  These must be completed by the contributor, with help if required from the POC or FINOS Infra.   

## Logo / Trademarks
 - [x] Initiate transfer of trademarks to FINOS _(request help from help@finos.org / LF Legal if needed)_ - `sent form to contributor`
 - [x] Request logo design from `help@finos.org` _(if needed)_ - `building logo that adheres to FINOS standards, using existing logo image`
 - [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws. _(POC to validate with FINOS Legal team if anything important is raised)_

## FINOS Project Standards
- [x] Check GitHub repository transfer requirements:
  - [x] [finos-admin](http://github.com/finos-admin) has `Admin` to all repositories to transfer
  - [x] [finos-admin](http://github.com/finos-admin) ia allowed to transfer repositories out of the org
  - [x] if the repository is owned by a user (and not an org), the user must be able to transfer the repository to [finos-admin]
- [x] Apply project blueprint contents - see [ODP docs](https://community.finos.org/docs/collaboration-infrastructure#finos-project-blueprint)
    - [x] README.md file contains the sections in the [README Template](https://github.com/finos/software-project-blueprint/blob/main/README.template.md)
    - [x] Project FINOS badge in README (incubating)
    - [x] [OpenSSF Passing Badge](https://bestpractices.coreinfrastructure.org/en)
    - [x] License in README
    - [x] Contributing in README
    - [x] `CONTRIBUTING.md`
    - [x] `LICENSE` (replace `{}` placeholders)
    - [x] Ensure that the proper project governance is in the CONTRIBUTING.md file
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are checked and documented below

_Add documentation here_

# 4.  FINOS Onboarding

This is performed by FINOS Infra once the three previous stages are complete, with support from the contributor and the FINOS POC.

## Maintainers, Contributors and CLAs 
- [x] Identify other existing contributors (assuming there's a contribution history (eg Git history)
- [x] Check if maintainers and other contributors are all covered by FINOS CLA
- [x] Engage with FINOS Legal team to figure out what’s needed to cover all maintainers and contributors with FINOS CLA
- [x] Reach out to contributors and employers to coordinate CLA signatures

## Validation (only if code is contributed) 
- [x] The codebase doesn’t have HIGH or CRITICAL CVEs across direct and transitive libraries
- [x] The codebase doesn’t have any unfriendly licenses across direct and transitive libraries
- [x] (optional - if a build system is provided) The build process runs successfully
(http://github.com/finos-admin)
- [x] The codebase doesn’t include any patent or copyright that conflicts with FINOS Governance and bylaws (to be validated with FINOS Legal team)
- [x] [All incubating criteria](https://community.finos.org/docs/governance/Software-Projects/stages/incubating) are met (review documentation provided above)

## Code transfer and repo setup
- [x] Transfer all code assets as GitHub repositories under github.com/finos
- [x] Invite GitHub usernames to GitHub FINOS Org
- [x] Configure `finos-admins` (`Maintain` role) and `finos-staff` (`Triage` role) team permissions
- [x] Link communication channels linked front-and-center in the project README.md
- [x] Add project maintainers emails to [finos-project-maintainers@finos.org](https://groups.google.com/a/finos.org/g/finos-project-maintainers/members) list
- [x] Add project maintainers GitHub usernames to the [project-maintainers Team](https://github.com/orgs/finos/teams/project-maintainers/members)
- [x] Create `<project-name>-maintainers` GitHub team and invite users -  https://github.com/orgs/finos/teams/regulartable-maintainers
- [x] Enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) (`Require a pull request before merging`)
- [x] Ask @jgavronsky to mark contribution as "Active" within LF systems
- [x] Add project to metadata
- [x] Add identities, orgs and affiliations to metadata (deprecated by EasyCLA)
- [x] Add logo to FINOS landscape
    - [x] Create `staging` branch on `finos/finos-landscape`
    - [x] Merge `finos/metadata` changes on master (will udpdate `landscape.yml` in `finos/finos-landscape`)
    - [x] Create PR from `staging` branch on `finos/finos-landscape`
    - [x] Review Netlify preview
    - [x] Merge PR

# 5. Announcement 

(Lead: FINOS Contrib POC)

- [x] Update the contribution status to "Active" by sending another email to **LF Legal Representative** with the name of the project and its new status.
- [x] Lead maintainer works with FINOS marketing to send out announcement to announce@finos.org , checkout announcement template at the [Contribution page](https://community.finos.org/docs/governance/Software-Projects/contribution#step-5-contribution-announcements)
- [x] Notify FINOS marketing (@grizzwolf + finos-marketing internal Slack channel)

**Comment by robmoffat** [comment]
@maoo is this something we are trying get done before OSFF?

I am just talking with @ColinEberhardt and there is a TSC planned for 30th November.   He would be happy to have this on the agenda for that meeting, if the materials are ready in time and it gives you enough time after the meeting to complete the onboarding.

**Comment by ColinEberhardt** [comment]
@maoo can you please add @jonfreedman as an assignee? He is looking at this contribution on behalf of the TSC.

**Comment by maoo** [comment]
> @maoo can you please add @jonfreedman as an assignee? He is looking at this contribution on behalf of the TSC.

Done!

**Comment by jonfreedman** [comment]
I have reviewed this contribution against the TSC [contribution principles](https://github.com/finos/technical-steering-committee/blob/master/contribution-principles.md) and note the following.

**Contributions must be aligned with the purpose of FINOS**
It’s my understanding that the project solves a very specific async rendering use case that at the time of the projects inception could not be solved using existing open source or commercial grid libraries which I see as an example of innovation. In addition I believe that alignment with the purpose of FINOS can be inferred from the popularity and adoption of Perspective which depends on this library (https://github.com/finos/perspective/blob/master/packages/perspective-viewer-datagrid/package.json#L46).
 
**A proposed standard must not compete with other FINOS standards**
This is not applicable as this is not a standard
 
**An open source project that is a component of a commercial offering must provide tangible value in its own right**
This is not applicable as this is not part of a commercial offering
 
**Contributions should generate interest within the member organisation**
The contribution is being jointly sponsored by both J.P. Morgan and Point72 showing interest at the contributor level across two member organisations, in addition interest can be inferred from the popularity and adoption of Perspective
 
**Contributions should be projects that deliver long-term value, with a team that supports this goal**
This is a mature project with 283 github stars and 1500+ weekly downloads on npm with 33 versions published over the last 3 years
 
**A proposed contribution that competes with an existing FINOS project should consider potential routes to a merge**
Assuming this is successfully contributed there is a case to be made for the project being owned by the existing Perspective project team rather than requiring a separate team

As such we give our recommendation **_in favor_** of the contribution.

We also note a couple of specific issues raised by the contributors based on the prior contribution process of Perspective by J.P. Morgan:
1.	Moving packages from one npm co-ordinate to another and deprecating the original was felt to have a strong negative impact on project visibility
I don’t see anything particularly obvious here but the “package has been deprecated” message is not great
https://www.npmjs.com/package/@jpmorganchase/perspective
https://npmtrends.com/@finos/perspective-vs-@jpmorganchase/perspective

2.	Updating the project readme.md to add an “incubating” badge was felt to give a negative impression to existing users of a reduction in project quality
Some anecdotal evidence of internal calls and queries within J.P. Morgan asking whether an issue had been found with the project has been shared with me

To address the first of the contributors concerns the TSC support the dual-publishing of the library under both the existing un-scoped npm co-ordinate and a new @finos/regular-table for a suitable period of time without deprecating the original, ideally being able to observe a decline in the un-scoped package on npmtrends.com. The TSC suggests this is discussed further as part of on-boarding.
 
The TSC does not attempt to address the second contributor concern around badging of the project or its incubating vs active status and leaves this to be addressed between the project team and the FINOS staff as part of the project on-boarding.

Any additional quantitative evidence around these two concerns would be welcomed!

**Comment by TheJuanAndOnly99** [comment]
Contribution is pending on this PR https://github.com/finos/regular-table/pull/175 being merged

**Comment by mindthegab** [comment]
Since @TheJuanAndOnly99 the PR above was merged, the only remaining item is to send an email to announce@ - @texodus / @neilslinger do you guys plan to do that?
