### ISSUE TITLE
Project Communication Channels Etiquette

### ISSUE THREAD

**Issue by brooklynrob** [finos/community#59]
Historically, and again more recently, the foundation has received questions about what's fair game to be distributed through project specific communication channels, the Google Groups mailing lists in particular. 

The guidance I provided project leads while Director of Programs was that a project's google group mailing list may be used to share training, documentation, articles, webinars that a community participant (either individual or org) has developed/produced provided it is:

1. free of charge, AND
2. directly related to the work/output/code bases of our project.

So, for example, a free webinar on how to develop a Python application on Perspective would be fair play for an organization (whether FINOS member or not) to share through the Perspective mailing list. A paid training on how to program in Python though would be not as 1) it's not free and 2) it's not specific to a FINOS project. 

I think it would be good to affirm this policy and codify here in the revised governance, but not sure where exactly it should go.

This might be also be an opportunity to clarify to the community that it's project leads responsibilities - not FINOS staff - to moderate their project's google group messages (and join requests), perhaps as part of further codifying duties and expectations of project leads.

**Comment by brooklynrob** [comment]
Worth noting the Foundation has taken a generally more inclusive approach towards what events, training, to include on 1) the FINOS event calendar (https://www.finos.org/news-and-events) and 2) This Week at FINOS ("TWAF"), with a general bias toward events in which FINOS members are involved (e.g,. speaking at), are sponsoring, etc., and with a preference towards those that are related to FINOS projects and/or strategic initiatives, though we also share industry and open source events we think are of general interest to our community via those channels.

A difference is that the Google Groups mailing lists are first and foremost for project collaboration, and as such the general desire is that posts to the mailing lists be directly relevant to the project scope itself.

**Comment by jessicameiselman** [comment]
Thanks for raising this issue Rob. Here are some thoughts from OpenFin.
 
We don't think issues like this should be delegated to project leads. As with the Code of Conduct, we think it would be better for FINOS to implement a consistent policy across all FINOS projects and working groups. 
 
We’re skeptical of the “no fee” approach. This ignores that there are other commercial benefits to be obtained by individuals advertising their events in a group. Furthermore, there are privacy implications if we allow commercial use of the message boards (e.g. users have opted in for a particular purpose, not for their info to be used for marketing purposes). We’re also concerned about a competitive dynamic that creates a race between multiple Members to promote their services (free or otherwise).
 
Our view is that it is cleaner for FINOS to simply enact a broad non-solicitation policy. There are plenty of venues for people to promote their products and services including their own social networks, mailing lists, conferences, press, etc. We feel that allowing promotion goes against the spirit of the group and encourages further promotion.
 
Most non-profit educational focused groups and communities enact a non-solicitation policy. Here’s what we propose: "The spirit of this group is to share information and materials that enrich the community -- you may not use FINOS or its various project groups to solicit customers, clients, or other commercial partnerships for your benefit."
